version: '3.8'

services:

  postgres:
    image: postgres:13-alpine
    container_name: sites-database-postgres
    env_file:
      - app/.env
    args:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_SERVER : ${POSTGRES_SERVER}
      POSTGRES_PORT : ${POSTGRES_PORT}
      POSTGRES_DB : ${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - sites-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  fastapi:
    build: ./app
    ports:
      - 8002:8000
    container_name: sites-backend-fastapi
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    links:
        - postgres:postgres
    networks:
        - sites-network

volumes:
  postgres-volume:

networks:
  sites-network:
    driver: bridge
